### ISSUE TITLE
Continuous Clicking Feature Proposal for xclicker Project

### ISSUE THREAD

**Issue by GloryPkqa** [robiot/xclicker#95] opened 2024-05-05 01:42 UTC
Propose adding a feature to the xclicker project enabling continuous clicking when the mouse button is held down, eliminating the need for manual repetitive clicking without the requirement of using hotkeys.

**Comment by robiot** [comment] 2024-11-14 11:06
Duplicate of #12 

Have a great day 🫡

**Closed by robiot** 2024-11-14 11:06 UTC
